Repository DevBlocky/scalpel, pull requests merged in 2021-05, with the labels that each got.

#14 Fix conversion number in backend ping
  src/backend.rs
Labels: bug

#16 Negative max_grace_period
  settings.sample.yaml
  src/config.rs
  src/main.rs
Labels: enhancement

#15 Less String Clones
  src/backend.rs
  src/cache/mod.rs
  src/http/handler.rs
  src/http/mod.rs
Labels: bug

#13 Add `fs` Cache Engine
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  settings.sample.yaml
  src/cache/fs.rs
  src/cache/mod.rs
  src/cache/rocks.rs
  src/config.rs
  src/main.rs
Labels: enhancement

#18 tweak: swap all RwLocks for ArcSwaps
  Cargo.lock
  Cargo.toml
  src/backend.rs
  src/http/handler.rs
  src/http/mod.rs
  src/main.rs
Labels: enhancement

#19 Follow Spec for Token Errors
  src/tokens.rs
Labels: bug

#20 Init changes for HttpServer
  src/http/mod.rs
Labels: bug, enhancement

#23 fix: Add timeouts to HTTP Clients
  src/backend.rs
  src/http/handler.rs
Labels: bug
